spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true

  profiles:
    active: loadInitialData

# run on port 8081
#server:
#  port: 8081